#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

OLDIFS="$IFS"
IFS=" "
SUBCOMMAND="$1"
DOKKURC=${DOKKURC:="/home/dokku/dokkurc"}
DOKKURC_LINE=${DOKKURC_LINE:="export DOKKU_TRACE=1"}

if [ $# -lt 1 ] && [ "$1" != "help" ]
then
  SUBCOMMAND=help
fi

case "$SUBCOMMAND" in
  debug)
    if ! [ -f "$DOKKURC" ] ; then
      echo Tracing is disabled.
    elif grep "$DOKKURC_LINE" "$DOKKURC"  ; then
      echo Tracing is enabled.
    else
      echo Tracing is disabled.
    fi
    ;;
  debug:on)
    echo "$DOKKURC_LINE" >> "$DOKKURC"
    ;;
  debug:off)
    TMPFILE=$(mktemp)
    (grep -v "$DOKKURC_LINE" "$DOKKURC" > "$TMPFILE") || true
    mv "$TMPFILE" "$DOKKURC"
    ;;
  debug:toggle)
    if [ "$0" debug | grep -i enabled ] ; then
      "$0" debug:on
    else
      "$0" debug:off
    fi
    ;;
  help)
   cat && cat<<EOF
    debug                                           show current setting
    debug:on                                        activate tracing
    debug:off                                       deactivate tracing
    debug:toggle                                    toggle tracing
EOF
    ;;
esac

IFS="$OLDIFS"