#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
[[ " help $PLUGIN_COMMAND_PREFIX:help " == *" $1 "* ]] || [[ "$1" == "$PLUGIN_COMMAND_PREFIX:"* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_BASE_PATH/common/functions"

case "$1" in
  debug)
    "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/subcommands/default" "$@"
    ;;

  debug:off)
    "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/subcommands/off" "$@"
    ;;

  debug:on)
    "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/subcommands/on" "$@"
    ;;

  debug:toggle)
    "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/subcommands/toggle" "$@"
    ;;

  help | $PLUGIN_COMMAND_PREFIX:help)
    help_content_func() {
      # shellcheck disable=SC2034
      declare desc="return $PLUGIN_COMMAND_PREFIX plugin help content"
      cat<<help_content
    $PLUGIN_COMMAND_PREFIX, displays the current trace status
    $PLUGIN_COMMAND_PREFIX:on, activate trace mode
    $PLUGIN_COMMAND_PREFIX:off, deactivate trace mode
    $PLUGIN_COMMAND_PREFIX:toggle, toggle trace mode
help_content
    }

    help_list_func() {
      # shellcheck disable=SC2034
      declare desc="return $PLUGIN_COMMAND_PREFIX plugin help content"
      cat<<help_list
-----> Enabling dokku trace
help_list
    }

    if [[ $1 = "$PLUGIN_COMMAND_PREFIX:help" ]] ; then
      echo -e "Usage: dokku $PLUGIN_COMMAND_PREFIX[:COMMAND]"
      echo ''
      echo "Manages dokku trace mode"
      echo ''
      echo 'Example:'
      echo ''
      echo "\$ dokku $PLUGIN_COMMAND_PREFIX:on"
      help_list_func
      echo ''
      echo 'Additional commands:'
      help_content_func | sort | column -c2 -t -s,
    elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
      help_content_func
    else
      cat<<help_desc
    $PLUGIN_COMMAND_PREFIX, Plugin for managing trace mode
help_desc
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;
esac
