#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

debug-on-cmd() {
  declare desc="activate trace mode"
  local cmd="debug:on"
  [[ "$1" == "$cmd" ]] && shift 1

  [[ -d $DOKKU_ROOT/.dokkurc ]] || mkdir -p "$DOKKU_ROOT/.dokkurc"

  if [[ ! -f "$DOKKU_ROOT/.dokkurc/DOKKU_TRACE" ]]; then
    dokku_log_info1 "Enabling dokku trace"
    echo "export DOKKU_TRACE=1" > "$DOKKU_ROOT/.dokkurc/DOKKU_TRACE"
  else
    dokku_log_info1 "Trace mode already enabled"
  fi
}

debug-on-cmd "$@"
