#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

debug-toggle-cmd() {
  declare desc="toggle trace mode"
  local cmd="debug:toggle"
  [[ "$1" == "$cmd" ]] && shift 1

  [[ -d $DOKKU_ROOT/.dokkurc ]] || mkdir -p "$DOKKU_ROOT/.dokkurc"

  if [[ -f "$DOKKU_ROOT/.dokkurc/DOKKU_TRACE" ]]; then
    dokku_log_info1 "Disabling dokku trace"
    rm -f "$DOKKU_ROOT/.dokkurc/DOKKU_TRACE"
  else
    dokku_log_info1 "Enabling dokku trace"
    echo "export DOKKU_TRACE=1" > "$DOKKU_ROOT/.dokkurc/DOKKU_TRACE"
  fi
}

debug-toggle-cmd "$@"
